name: luxkitchen-dev
services:
  db:
    image: postgres:15
    ports:
      - '5492:5432'
    restart: on-failure
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydb']
      retries: 4
      interval: 5s
      timeout: 3s
    environment:
      POSTGRES_USER: luxkitchen 
      POSTGRES_PASSWORD: luxkitchen
      POSTGRES_DB: luxkitchen

    volumes:
      - db_data:/var/lib/postgresql/data

  s3:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - '9000:9000'
      - '9090:9090'
    restart: on-failure
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9090"
    volumes:
      - s3_data:/data

volumes:
  db_data:
  s3_data:
